test: spec-examples spec-examples-by-section

spec-examples:
	PYTHONPATH=..:$(PYTHONPATH) python uritemplate_test.py cases/spec-examples.json 4

spec-examples-by-section:
	PYTHONPATH=..:$(PYTHONPATH) python uritemplate_test.py cases/spec-examples-by-section.json 4
